# Generated by Django 4.2.7 on 2025-03-27 16:32

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='slug',
        ),
        migrations.AddField(
            model_name='softwaresolution',
            name='slug',
            field=autoslug.fields.AutoSlugField(blank=True, editable=False, max_length=200, null=True, populate_from='title', unique=True),
        ),
    ]
