# Generated by Django 4.2.7 on 2025-03-27 16:45

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_remove_blogpost_slug_softwaresolution_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='category',
            field=models.CharField(choices=[('ai_technology', 'AI Technology'), ('machine_learning', 'Machine Learning'), ('data_science', 'Data Science'), ('business_intelligence', 'Business Intelligence'), ('industry_insights', 'Industry Insights'), ('case_studies', 'Case Studies'), ('company_news', 'Company News')], default='ai_technology', max_length=50),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='slug',
            field=autoslug.fields.AutoSlugField(blank=True, editable=False, max_length=200, null=True, populate_from='title', unique=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='tags',
            field=models.CharField(blank=True, help_text='Comma-separated tags', max_length=200),
        ),
    ]
