# Generated by Django 4.2.7 on 2025-03-27 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_blogpost_category_blogpost_slug_blogpost_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryimage',
            name='category',
            field=models.CharField(choices=[('events', 'Events'), ('team', 'Team'), ('office', 'Office'), ('products', 'Products'), ('clients', 'Clients'), ('awards', 'Awards')], default='events', max_length=50),
        ),
    ]
