# Generated by Django 4.2.7 on 2025-03-27 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_galleryimage_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_upcoming',
            field=models.BooleanField(default=True),
        ),
    ]
